### ISSUE TITLE
onclick events possible?

### ISSUE THREAD

**Issue by maximmcnair** [carlcraig/tc-angular-chartjs#10]
Hi, I'm wondering how onClick events can be implemented through angular?

**Comment by ab712** [comment]
I create the models for 6-10 charts and render them in an ng-repeat.  I need access to just one of the chart objects so I tried using ng-if and a flag in the model with two canvas elements.  Everything works except getting a single scope value to reference that one chart.  Any other suggestions for accessing the chart?  Is it available directly from canvas element if I use jquery from the controller?
