### ISSUE TITLE
Are global chart options available?

### ISSUE THREAD

**Issue by kazyn** [carlcraig/tc-angular-chartjs#23]
Hi, hopefully this isn't a severely dim-witted question but are global chart configs available? I was thinking maybe it was rolled into  'chart-options' but things like 'tooltipTemplate' don't seem to work. I've successfully used 'legendTemplate' from the individual chart options but cannot get the global settings correctly configured.

Thank you for reading,
G

**Comment by carlcraig** [comment]
Hi,

I haven't tested out `tooltipTemplate` fully. Have you got an example where this is not working? I know legendTemplate works, might be an issue Chart.js side of things.

If you could get an example with tooltip template so I can take a look it would be perfect.

Thanks.

**Comment by joel1st** [comment]
Can confirm - tooltipTemplate doesn't seem to work for the Line Chart - but works for pie chart.
