### ISSUE TITLE
Showing data values

### ISSUE THREAD

**Issue by khwerhahn** [carlcraig/tc-angular-chartjs#24]
How do I display the the values in a Doughnut Chart? I want them to be shown permanently and not only on hover.

**Comment by carlcraig** [comment]
This is more a `Chart.js` problem.

It seems that tooltips are bound to show/hide based on mouse events. However it is possible to create custom tooltips. I would advise you to experiment with custom tooltips.

http://www.chartjs.org/docs/#advanced-usage-external-tooltips

```js
var myPieChart = new Chart(ctx).Pie(data, {
    customTooltips: function(tooltip) {

        // tooltip will be false if tooltip is not visible or should be hidden
        if (!tooltip) {
            return; // REMOVE this? could potentially always show tooltips?
        }
        // ...
    };
});
```

To get that to work you should add the `customTooltips` property to your `chart options` and potentially remove the `return;` above.
