### ISSUE TITLE
Usage inside ng-repeat?

### ISSUE THREAD

**Issue by RPieter** [carlcraig/tc-angular-chartjs#27]
How do you use this inside a repeater?
I've tried both
```javascript
<div class="panel chart-box" ng-repeat="chart in stats.charts">
    <canvas tc-chartjs-line chart-options="chartoptions" chart-data="chart.data" auto-legend></canvas>
</div>
```
as
```javascript
<div class="panel chart-box" ng-repeat="chart in stats.charts" ng-init="chartdata=chart.data">
    <canvas tc-chartjs-line chart-options="chartoptions" chart-data="chartdata" auto-legend></canvas>
</div>
```
but in all cases, no charts are shown (debugging shows that there is no data).
Am I doing something wrong or is this not possible?

**Comment by carlcraig** [comment]
not sure on this, try:

```js
<div class="panel chart-box" ng-repeat="chart in stats.charts" >
    <canvas tc-chartjs-line chart-options="chart.options" chart-data="chart.data" auto-legend>
    </canvas>
</div>
```

Where `options` and `data` are properties on your `stats.charts` objects

**Comment by RPieter** [comment]
sorry, my bad.
in php, I returned the data-section as a nameless object.
By simply adding the name-value this worked.
Should have seen this far sooner!
