### ISSUE TITLE
Some questions about the chart

### ISSUE THREAD

**Issue by simo94** [carlcraig/tc-angular-chartjs#29]
I'd like to know if there is a way to zoom after i click on a part of the chart. I mean... as you see here i have a chart-line. I'd like to click on the red circle (day n°4) and it has to zoom in and show me 3 days before day n°4 and 3 days after. It has to zoom on click. The same thing must work on the other days.
Is there a way to do that? thanks :)
![screenshot](https://cloud.githubusercontent.com/assets/5559523/5939645/ce60d46e-a705-11e4-9b02-63c2f0c21599.png)

The other thing i've noticed is that if you reload the page with the canvas display none, the graph won't show up even if you toggle dislplay none from the style. It shows only the legend. So i must reload the page to see the graph and there's no way to hide it on reload page. I must show it only when i click on a certain button.

Can you please give me some information about these things? Thanks again. :D

**Comment by carlcraig** [comment]
Hi there. I am unsure on the first part regarding zooming, maybe updating the dataset on click could do that?

For the chart breaking when hidden there is an open issue for this that is yet to be solved: #9 

For creating click events there is another issue with some examples: #10 

Let me know if any of this is useful.
