### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by simo94** [carlcraig/tc-angular-chartjs#31]
Is there a way to customize the tooltip? I mean adding some css to it..

**Comment by carlcraig** [comment]
Hi

I would start by looking at http://www.chartjs.org/docs/#getting-started-global-chart-configuration to see if the options for tooltips and tooltip templates will offer what you are looking for there is also a section regarding external tooltips http://www.chartjs.org/docs/#advanced-usage-external-tooltips.

Let me know if you have any luck with this. C

**Comment by simo94** [comment]
![capture](https://cloud.githubusercontent.com/assets/5559523/6345904/ba1ccbe2-bc0a-11e4-92d4-31bfd07851fe.png)
Hi Carl,
thanks for replying me so fast. I've already checked all the chart.js documentation but that didn't help me much. I need to modify my tooltip to look somewhere near as the one in the picture.

**Comment by carlcraig** [comment]
Hi,

Take a look at #24 which is to remove tooltips (not sure if it works). I think custom tooltips or tooltipsTemplate may help you. Also look at http://www.chartjs.org/docs/#advanced-usage-external-tooltips.

Example tooltip customization http://jsfiddle.net/rpxLmu88/2/

Also check:
- https://github.com/nnnick/Chart.js/blob/master/samples/pie-customTooltips.html
- https://github.com/nnnick/Chart.js/blob/master/samples/line-customTooltips.html
