### ISSUE TITLE
Nothing but PIE works

### ISSUE THREAD

**Issue by kthnxbye** [carlcraig/tc-angular-chartjs#32]
Hi, hope you Ok

Im having this weird issue with the lib, i cant make any chart to work but PIE one, this is my example

/*Using jade*/
canvas(tc-chartjs-doughnut chart-options="vm.options" chart-data="vm.data")

it just goes and render a pie chart, same with line, bar .. and whatnot

is dat a bug or am i doing something wrong?

ill post my controller as well

/*Ctrl*/

(function() {
	'use strict';

	angular
		.module('4kidz')
		.controller('Reports', Reports);

		Reports.$inject = ['$rootScope'];

		function Reports($rootScope) {

			var vm = this;
			
			vm.data = [
	      {
	        value: 300,
	        color:'#F7464A',
	        highlight: '#FF5A5E',
	        label: 'Red'
	      },
	      {
	        value: 50,
	        color: '#46BFBD',
	        highlight: '#5AD3D1',
	        label: 'Green'
	      },
	      {
	        value: 100,
	        color: '#FDB45C',
	        highlight: '#FFC870',
	        label: 'Yellow'
	      }
	    ];

	    // Chart.js Options
	    vm.options =  {

	      // Sets the chart to be responsive
	      responsive: true,

	      //Boolean - Whether we should show a stroke on each segment
	      segmentShowStroke : true,

	      //String - The colour of each segment stroke
	      segmentStrokeColor : '#fff',

	      //Number - The width of each segment stroke
	      segmentStrokeWidth : 2,

	      //Number - The percentage of the chart that we cut out of the middle
	      percentageInnerCutout : 0, // This is 0 for Pie charts

	      //Number - Amount of animation steps
	      animationSteps : 100,

	      //String - Animation easing effect
	      animationEasing : 'easeOutBounce',

	      //Boolean - Whether we animate the rotation of the Doughnut
	      animateRotate : true,

	      //Boolean - Whether we animate scaling the Doughnut from the centre
	      animateScale : false,

	      //String - A legend template
	      legendTemplate : ''

	    };

		}

})();

**Comment by carlcraig** [comment]
Not sure what's going on there.

Are you changing the directive when you want to show different charts? 

It's currently set to `tc-chartjs-doughnut` which would make it show a doughnut char every time. You can try changing that to any of the following: 

- tc-chartjs-line
- tc-chartjs-bar
- tc-chartjs-radar
- tc-chartjs-polararea
- tc-chartjs-pie
- tc-chartjs-doughnut

Alternatively you could try using the other directive `tc-chartjs` with `chart-type="line"` where you can specify the chart type e.g:

```html
<canvas tc-chartjs chart-type="line" chart-data="vm.data" chart-options="vm.options"></canvas>
```

Also make sure your `options` and `data` are correct for the type of chart you are making. Have a look at some of the examples (***line example***: http://carlcraig.github.io/tc-angular-chartjs/line/)

Let me know if this solves your problem.

**Comment by kthnxbye** [comment]
yup im sure i've changed it but it just doesn't work as it should im literally copy-ing and paste-ing from the page http://carlcraig.github.io/tc-angular-chartjs/doughnut/
