### ISSUE TITLE
grunt build error

### ISSUE THREAD

**Issue by khwerhahn** [carlcraig/tc-angular-chartjs#33]
Hi,

when I try to use grunt for some tasks I get the following error:

Warning: Unable to read "dist/client/bower_components/Chart.js" file (Error code: EISDIR). Use --force to continue.

AND:

Running "usemin:js" (usemin) task

Processing as JS - dist/client/app/b1767f47.vendor.js
Update the JS to reference our revved images

Processing as JS - dist/client/app/d2b1e490.app.js
Update the JS to reference our revved images

Processing as JS - dist/client/bower_components/Chart.js
Warning: EISDIR, illegal operation on a directory Used --force, continuing.

The "Chart.js" seems to be the problem, as a dot is bad practice to include in directory names

I have another issue open in angular-fullstack-generator: https://github.com/DaftMonk/generator-angular-fullstack/issues/898

**Comment by carlcraig** [comment]
I'm not sure about this issue, it's definitely a problem with the build system you are using, although i am unsure on what files you are trying to include.

This library should be accessible at `bower_components/tc-angular-chartjs/dist/tc-angular-chartjs.min.js` when it is installed via bower.

Bower should also install the `Chart.js` library as it is a dependency for this library. Allowing you to access the Chart.js library at `bower_components/Chart.js/Chart.min.js`.

Your build system seems to be trying to include `dist/client/bower_components/Chart.js` which is not the correct path for Chart.js... it would most likely be `dist/client/bower_components/Chart.js/Chart.min.js`. If tc-angular-chartjs is also installed via bower, then you should probably be including `dist/client/bower_components/tc-angular-chartjs/dist/tc-angular-chartjs.min.js`.

Let me know if you solve your problem so as I can close this issue.

**Comment by khwerhahn** [comment]
@carlcraig Thank you for your help. I guess I will have to open an issue in Chart.js. The problem seems to be there since the repos is called Chart.js. I cannot be the only one with this problem (hopefully).
