### ISSUE TITLE
Pie and Doughnut chart specific click

### ISSUE THREAD

**Issue by simo94** [carlcraig/tc-angular-chartjs#34]
Is there a way to impement on click on a single part of the graph?
I mean... can i open an alert by clicking on the green part and an url by clicking on the red one?

thanks
![selezione_034](https://cloud.githubusercontent.com/assets/5559523/7293044/2d42c540-e9a1-11e4-8979-732bd4884107.png)

**Comment by carlcraig** [comment]
hi,

take a look at issue #10 as this has a small example of click events

**Comment by simo94** [comment]
I've already tried that but when i click on the doughnut it disappears and the activePoints is an empty array. When i scroll down my page, the doughnut appears again.
This is my code:
var ctx = angular.element(document.getElementById("chart" + index).getContext("2d"));
var myNewChart = new Chart(ctx[0]).Doughnut($scope.data,$scope.options);
var activePoints = myNewChart.getSegmentsAtEvent(event);

**Comment by carlcraig** [comment]
take a look at the example in #10 http://jsfiddle.net/Lfmhcab3/4/

Check the console for output when you click a point.
