### ISSUE TITLE
Is it possible to make a horizontal bar chart with this?

### ISSUE THREAD

**Issue by arjunroychowdhury** [carlcraig/tc-angular-chartjs#36]
Hi,  Is it possible to make a horizontal bar chart with this? I've seen people post plugins to chart.js for horizontal bar charts, but not sure how to use them with this directive version

**Comment by carlcraig** [comment]
I think this should be possible (although I have not tested this)

Chart.js has `line, bar, radar, polararea, pie and doughnut` chart types, if a plugin was to provide a custom chart type, then you could make it work (http://www.chartjs.org/docs/#advanced-usage-writing-new-chart-types).

For example the https://github.com/Regaddi/Chart.StackedBar.js extension for chartjs provides a `StackedBar` chart type.

To make this StackedBar chart type work with tc-angular-chartjs you can use the `tc-chartjs` directive or create a new directive for it:

Example Using `tc-chartjs` directive

```html
<canvas tc-chartjs chart-type="StackedBar" chart-data="data" chart-options="options">
</canvas>
```

Example creating a directive `tc-chartjs-stacked-bar` using `TcChartjsFactory`

```js
angular
    .module('your-app', ['tc.chartjs')
    .directive('tcChartjsStackedBar', TcChartjsStackedBar);

function TcChartjsStackedBar(TcChartjsFactory) {
    return new TcChartjsFactory( 'StackedBar' );
}
```

The easiest way is to use the `tc-chartjs` directive and provide the custom chart type in the `chart-type` attribute.

Let me know if this helps.

**Comment by arjunroychowdhury** [comment]
Carl, this was an excellent tutorial in addition to an answer. Thank you!
