### ISSUE TITLE
Chart re render makes the canvas blurred

### ISSUE THREAD

**Issue by vishnukarthikl** [carlcraig/tc-angular-chartjs#37]
Whenever the underlying data of the chart changes, and after the re render, the chart looks a bit blurred. 
![screen shot 2015-05-11 at 10 00 18 am](https://cloud.githubusercontent.com/assets/1880140/7558571/02f5713e-f7c5-11e4-88e5-8615c0bd8a53.png)
![screen shot 2015-05-11 at 10 00 52 am](https://cloud.githubusercontent.com/assets/1880140/7558572/087b4642-f7c5-11e4-9bb5-d5fe3f14e182.png)

The crisp text is gone in the subsequent re renders.

**Comment by dmackerman** [comment]
Yeah, noticing this as well.

**Comment by vishnukarthikl** [comment]
Calling chartObj.resize() just before returning from $watch fixes the issue. But I'm stuck making the test pass. I am not able to add a method to the spy that is returned.

**Comment by atefBB** [comment]
Hi @vishnukarthikl!
How did you do to re-render the chart?! And did you use new data?!
