### ISSUE TITLE
Dynamic height?

### ISSUE THREAD

**Issue by pliablepixels** [carlcraig/tc-angular-chartjs#38]
Hi, In a previous correspondence, you helped me understand how to incorporate a new graph plugin using the tc-chart-type. That works superbly --> I am using HorizontalBar with tc-charts.

I wonder if you can help me with another situation - have you added any directive/wrapper that can help scale the height of the chart?

The predicament I am facing is this: If I have 30 bars, everything gets scrunched up. I'd like to specify a minimum bar height, say 40px. The graph should not reduce this height. If it needs to, it should overflow and add a vertical scroll bar. I've been tinkering with wrapping the canvas like so:

```
<div style="overflow:scroll;">
                        <canvas tc-chartjs chart-type="HorizontalBar" chart-data="data" chart-options="options" width="90%">
                        </canvas>
                    </div>
```
But this makes the canvas always overflow even when I have 2 or 3 bars - it makes the bar height too big. So I am not sure I can solve this with overflows - hence the thought about bar height

**Comment by carlcraig** [comment]
I am closing this for now.

Version 2.1.2 supports horizontal bar, please re-open this if you still have problems after upgrade.
