### ISSUE TITLE
tc-angular-chartjs x axis labels

### ISSUE THREAD

**Issue by ihabassi** [carlcraig/tc-angular-chartjs#40]
Hi, 
I there a way to "combine" the x axis labels when it to crowded?
for example when I'm having only 10 days on x axis it look nice but when it's 100 days I can't see anything.
I can see that it's doable on the original chart.js examples, but I'm not sure it doable in the directive.
Please take a look a the example.
https://developers.google.com/chart/interactive/docs/gallery/linechart
screen shot:
http://prntscr.com/77delm

**Comment by carlcraig** [comment]
im not sure on this. i think this is more of a chart.js related problem/feature.
