### ISSUE TITLE
ng-show ng-hide not working properly

### ISSUE THREAD

**Issue by vishnukarthikl** [carlcraig/tc-angular-chartjs#41]
I have a div which encloses a chart which has ng-show property on it. 

````html
<button ng-click="showGraph=!showGraph" ng-init="showGraph=false">toggle</button>
<div ng-show="showGraph">
  <canvas tc-chartjs-bar chart-data="data"></canvas>
</div>
````
But when showGraph property is changed to `true`, the div becomes visible but the graph is not rendered. But where as if `ng-init="showGraph=true"` is set then the chart is rendered properly first and the subsequent toggle work fine. I also checked the same for pie chart and ng-show/hide is working fine.

**Comment by carlcraig** [comment]
This is linked to #9, the current solution is to use `ng-if` instead until we find a fix for this issue
