### ISSUE TITLE
Chart Does Not Render if Placed on Hidden Tab-Pane

### ISSUE THREAD

**Issue by dayres** [carlcraig/tc-angular-chartjs#44]
When the chart is placed inside of a tab-pane that is hidden on page-load, the legend renders, but the chart content does not. (In this case, a bar chart)

**Comment by dayres** [comment]
I just saw there was an existing issue for this problem.

**Comment by yaronguez** [comment]
Where is the existing issue?  How do you fix this without a $timeout?

**Comment by kikocastro** [comment]
Solved by changing this:

`chartObj.resize();`

To:

```
if (chartObj.chart.canvas.parentNode.clientHeight !== 0 && chartObj.chart.canvas.parentNode.clientWidth !== 0) {
  chartObj.update();
}
```

Version 1.0.15
