### ISSUE TITLE
Graphs too wide in Bootstrap

### ISSUE THREAD

**Issue by letterix** [carlcraig/tc-angular-chartjs#45]
When I place a line chart inside a bootstrap panel body, the graph is 30 pixels too wide. It seems that the width calculation doesn't account for padding in the parent container (15px left, 15px right).
This hack fixes it for me:
```
canvas {
	padding-right: 30px;
}
```

This is the html:
```
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-body">
				<canvas tc-chartjs chart-type="line" chart-data="data" chart-options="myOptions" auto-legend></canvas>
			</div>
		</div>
	</div>
</div>
```

**Comment by SarasArya** [comment]
I am facing the same issue...

**Comment by carlcraig** [comment]
I think this is most likely a chart.js issue.

If you are still facing this problem please look at opening an issue on chart.js https://github.com/chartjs/Chart.js/issues
