### ISSUE TITLE
chart-doughnut inside ng-repeat

### ISSUE THREAD

**Issue by yosser22** [carlcraig/tc-angular-chartjs#47]
Hi everybody,

I'm trying to show multiple charts inside of ng-repeat. I don't know what I'm doing worng, but It is not showing any charts.
```
<div class = "box-body" id = "{{'criterion_'+ $index}}">
	{{criterion.data}}
<canvas id = "{{'doughnut_'+ $index}}" class="chart chart-doughnut" data = "criterion.data" labels="labels" colours= "colours">
</canvas> 
</div>
```
criterion.data shows the correct data.

Thank you!!

**Comment by carlcraig** [comment]
Hi,

Make sure you are using the correct directives e.g.


    <canvas tc-chartjs-doughnut chart-data="criterion.data" chart-options="options"></canvas>

Let me know if this solves your problem.

**Comment by yosser22** [comment]
Thank you :). It worked like a charm!!
