### ISSUE TITLE
chartObj.resize() shrinks canvas to 0x0 pixels

### ISSUE THREAD

**Issue by jsuiker** [carlcraig/tc-angular-chartjs#48]
I patched my installation together with some duct tape, but some help with a proper solution would be much appreciated.

f09c5dfa7745e49c2d36b98a3a881cc0c5a2ae86

**Comment by m0ngr31** [comment]
@jsuiker, worked for me too. Thanks

**Comment by carlcraig** [comment]
I think 2.X version should solve this problem. Please re-open this if the problem occurs after upgrading to chart.js 2.x and tc-angular-chartjs 2.x

**Comment by jsuiker** [comment]
awesome, i'll test it whenever i get a chance to update my project... Many thanks for your time!
