### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by kapil019** [carlcraig/tc-angular-chartjs#49]
Can i show tc-angular-bar-chart as horizontal?

**Comment by kapil019** [comment]
I need to show bar chart horizontaly,

Pease revert how i can do this.

**Comment by Zeioth** [comment]
It might be of your interest. 
http://stackoverflow.com/questions/26033080/creating-a-horizontal-bar-chart-extension-on-chart-js

**Comment by carlcraig** [comment]
This is now supported in `2.1.2`
