### ISSUE TITLE
Need to show value in pie chart

### ISSUE THREAD

**Issue by kapil019** [carlcraig/tc-angular-chartjs#50]
I need to show a value like https://cloud.githubusercontent.com/assets/5559523/6345904/ba1ccbe2-bc0a-11e4-92d4-31bfd07851fe.png

**Comment by SarasArya** [comment]
I have the same issue... Did you get an answer to it?

**Comment by justin-nodeboy** [comment]
+1, looks like you should be able to use the `chart-legend="true"` tag but alas it throws the following error in chrome. `angular.js:12330 ReferenceError: segments is not defined`

**Comment by ayastreb** [comment]
@kapil019, @SarasArya, @justin-nodeboy 
I'm doing it with CSS and a separate element for value inside the pie chart.
You can check how it looks [here](https://app.meal-planner.org/#/recipes/view/AVBteWIwyceyEzY1A0iD) (go to Nutrition tab), and the implementation is [here](https://github.com/meal-planner/client/blob/master/app/modules/nutrients/views/energy-chart.html)

**Comment by kapil019** [comment]
Thanks @ayastreb let me try this.

**Comment by carlcraig** [comment]
Going to close this as there seems to be some form of solution.

Please re-open this if there is still a problem.
