### ISSUE TITLE
Multi-coloured Bars?

### ISSUE THREAD

**Issue by cjwebdev** [carlcraig/tc-angular-chartjs#51]
Anyway to achieve multi-coloured bars (within each dataset)? I see there are forks of ChartJS that do this. EG:

fillColor : ["green","red","yellow","blue"],
strokeColor : ["green","red","yellow","blue"]

...But they don't seem to play well with this Angular directive.

Any guidance would be really appreciated.

**Comment by carlcraig** [comment]
I think this can now be achieved as we are using Chart.js 2.X

Please look at the updated data structures for Chart.js bar charts:

http://www.chartjs.org/docs/#bar-chart-data-structure

Also, make sure you update to 2.1.X version of this library to work with Chart.js 2.
