### ISSUE TITLE
Compatibility with Chart.js-2.0

### ISSUE THREAD

**Issue by chirag-20** [carlcraig/tc-angular-chartjs#52]
Any plans to make this directive compatible with Charts.js 2.0.

**Comment by kotmatpockuh** [comment]
+1

**Comment by joris-lambrechts** [comment]
You can now upgrade to version 2 which supports Chart.js 2!

**Comment by carlcraig** [comment]
Will close this now as Chart.js 2 support is now in thanks to @joris-lambrechts

**Comment by HudsonAfonso** [comment]
Chart.js-2.0 support Mixed charts, tc-angular-chartjs support Mixed charts?
