### ISSUE TITLE
How to combine two differents types of charts

### ISSUE THREAD

**Issue by equero** [carlcraig/tc-angular-chartjs#55]
There are any possible to create a barchart combined with line chart?¿. Is very hard to find a free library for commercial use.

If not, anyone know any jquery/angularjs directive/javascript lib to do that?

**Comment by SarasArya** [comment]
You can try amcharts.js It is a free library and one of the most beautiful ones.

**Comment by chirag-20** [comment]
I had written a simple [angularjs Directive for Charts.js](http://plnkr.co/edit/jDQFV62FSeXAQJ6o7jE8)
Charts.js v2.0 supports combined bar and line charts.

**Comment by carlcraig** [comment]
Version 2.1.X of this library is now working with Chart.js 2.x

Going to close this as there seems to be some solution.
