### ISSUE TITLE
Dynamic update of graph

### ISSUE THREAD

**Issue by PunkSage** [carlcraig/tc-angular-chartjs#6]
Is it possible to update the data dynamically without re-rendering the whole graph from scratch?

**Comment by mattjpenman** [comment]
Have to add my +1 - pretty keen for this

**Comment by albertpak** [comment]
any idea on how to do this? how to update a datapoint after chart has been created

**Comment by carlcraig** [comment]
I will take a look at some solution for this when i have time. If anyone else has some ideas on how to solve this, feel free to put together a PR, or some examples.

**Comment by dmackerman** [comment]
This is pretty crucial. Destroying the chart and re-creating almost seems more expensive than updating data points under the hood, especially in a UI where interaction and graphs are very frequent.

**Comment by cupofjoakim** [comment]
Another +1 from me. It feels very odd not to have this feature as it kind of goes against the angular-mentality.

**Comment by carlcraig** [comment]
Closing, as opened new issue for implementing this #43 can move any further discussion to that issue.
