### ISSUE TITLE
Receive Expression 'undefined' when upgrading to Angular 1.4.9

### ISSUE THREAD

**Issue by richfergus** [carlcraig/tc-angular-chartjs#60]
After upgrading to Angular 1.4.9, I receive this error
`Expression 'undefined' in attribute 'tcChartjsLine' used with directive '{2}' is non-assignable!`

It also happens on tcChartjsBar, tcChartjsDoughnut, tcChartjsRadar

**Comment by gpalomar** [comment]
same here!

**Comment by richfergus** [comment]
So nice to know it wasn't just me.... I have tried adjusting dependencies but to no avail..

**Comment by gpalomar** [comment]
me to, but nothing at yet

**Comment by Sithdown** [comment]
Me too. Any ideas?

**Comment by luke-adams** [comment]
There is a pull request with a fix for this here: https://github.com/carlcraig/tc-angular-chartjs/pull/59/files

I haven't tested that fix but, going on that fix, if you add these two attributes to your tc-chartjs elements it will "suppress" the error:
chart="" chart-legend="" 

for example:
<canvas tc-chartjs-line chart="" chart-legend="" chart-options="lineOptions" chart-data="lineData" auto-legend></canvas>

**Comment by AlexanderKozhevin** [comment]
+1

**Comment by Cordobo** [comment]
As the PR referenced by @luke-adams was merged in February, we only need a new release to omit this error
@carlcraig Could you create a new release please? Many thanks in advance!

**Comment by carlcraig** [comment]
Hi @Cordobo, this should already be part of `v1.0.15` which was published after the PR was merged. 

Hopefully #59 has solved this issue, would anyone be able to test this and let me know?

**Comment by Cordobo** [comment]
Hi @carlcraig - sorry if I caused any confusion - I was referring to the releases here (latest is 1.0.13)
https://github.com/carlcraig/tc-angular-chartjs/releases

It seems like bower is only looking for the "releases" and not the information provided in the bower.json

> bower ENORESTARGET  No tag found that was able to satisfy 1.0.15
> Additional error details:
> Available versions in git://github.com/carlcraig/tc-angular-chartjs.git: 1.0.13, 1.0.12, 1.0.11, 1.0.10,
> 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1

**Comment by carlcraig** [comment]
Ahh, thanks for noticing this.

I have just published new tag `v1.0.15` which will hopefully fix issue with bower.

Let me know if there are any other problems.

**Comment by Cordobo** [comment]
@carlcraig Thanks for the update, it fixed the issue with bower.

I just tested the new release 1.0.15 and can confirm there are no longer "non-assignable expression" errors in the console.

**Comment by richfergus** [comment]
Looks good to me as well, thank you!
