### ISSUE TITLE
How to add Custom legends ?

### ISSUE THREAD

**Issue by Krypternite** [carlcraig/tc-angular-chartjs#61]
I would like to show values along with labels in the pie and doughnut chart legends. Please tell how to do that. How to add custom legends in tc-angular-chartjs. I have seen the documentation but could not understand. Please Help.

**Comment by carlcraig** [comment]
This will be difficult to achieve as the legends are currently generated by Chart.js and i don't believe that there is much control outside of core Chart.js itself.

You might be better off to create your own legend outside of the chart?

Also, chart.js 2 seems to have nicer built in legends, it might be worth investigating that.

http://www.chartjs.org/docs/
https://github.com/chartjs/Chart.js/issues

I am going to close this for now, please re-open if there is an issue with this library.
