### ISSUE TITLE
ReferenceError: Chart is not defined

### ISSUE THREAD

**Issue by bharathrazoo** [carlcraig/tc-angular-chartjs#62]
I have included Chart.js and I still see the error Chart is not defined for some reason. 

```
module.exports =
  angular.module('mymodule', ['tc.chartjs'
  ])
```

my view 

` <canvas tc-chartjs-pie chart-options="options" chart-data="data" auto-legend></canvas>`

**Comment by carlcraig** [comment]
Are you still having this issue?

I am going to close this for now, please re-open if you are continuing to see this problem.
