### ISSUE TITLE
Chart.js 1.0.0-beta is no more on Bower.

### ISSUE THREAD

**Issue by haiderfaizan** [carlcraig/tc-angular-chartjs#64]
When using bower to download this plugin Chart.js is not downloaded.

**Comment by joris-lambrechts** [comment]
The version definition of Chart.js in the bower.json file states `~1.0.0-beta` which means any version `>= 1.0.0-beta` and  `< 2`.

When you run `bower install` it should use the latest `1.x.x` version of Chart.js, which is `1.1.1`.

Are you perhaps using a proxy repository? Maybe you could try clearing your bower cache: `bower cache clean Chart.js`

**Comment by carlcraig** [comment]
Going to close this now as bower support has been dropped by Chart.js and this library. 

There is a workaround for bower which is linked in the readme , and on Chart.js install instructions
