### ISSUE TITLE
Can't display chart for chart.js 1.1.1

### ISSUE THREAD

**Issue by spnettec** [carlcraig/tc-angular-chartjs#65]
Can not display chart any more when use chart.js 1.1.1.
change
line 114:
      chartObj.resize();
to 
     chartObj.update();

resove this problem

**Comment by tomsteg** [comment]
Please fix it.

**Comment by carlcraig** [comment]
feel free to submit a PR for this, it should ideally still support `object.resize()` unless `object.update()` exists. I am not sure when I will have time to do this change myself.

**Comment by joris-lambrechts** [comment]
Hi @carlcraig,

I fixed the issue but I can't create a pull request with a tag as base. If you need anything, let me know.

Kind regards,
Joris

**Comment by carlcraig** [comment]
Hi @joris-lambrechts I am happy to pull in the changes in your branch if you want?

Alternatively you might be able to use https://github.com/carlcraig/tc-angular-chartjs/tree/1.0 `1.0` branch as a base to get the PR to work? The `1.0` branch is sitting at version `1.0.15` currently.

**Comment by joris-lambrechts** [comment]
Hi @carlcraig,

I used the 1.0 branch, works like a charm! https://github.com/carlcraig/tc-angular-chartjs/pull/72

Joris

**Comment by carlcraig** [comment]
Thanks for this fix on this.

I will close this issue now as `v1.0.16` should solve this.
