### ISSUE TITLE
Chart Appears only on hover

### ISSUE THREAD

**Issue by Julan76** [carlcraig/tc-angular-chartjs#66]
Chart doesn't appear at the loading of the page. It appears only on hover.
I'm using    "Chart.js": "^2.1.3" and
    "tc-angular-chartjs": "^1.0.15"

**Comment by Walraz** [comment]
I have the same problem

**Comment by carlcraig** [comment]
This will hopefully be fixed as soon as I merge #69 which updates everything for Chart.js 2.X

**Comment by carlcraig** [comment]
Going to close this now as `2.X` is all setup to work with Chart.js 2
