### ISSUE TITLE
Receive TypeError(s) when upgrading to chart.js 2.1.3 and tc-angular 1.0.15

### ISSUE THREAD

**Issue by richfergus** [carlcraig/tc-angular-chartjs#68]
I receive this error when using tc-angular-chartjs.min.js:
`TypeError: h[c(...)] is not a function`

and this error when using tc-angular-chartjs.js

```
chart[cleanChartName(...)] is not a function
at Object.fn (tc-angular-chartjs.js:95
```
View:
`<canvas tc-chartjs-bar chart-options="options" chart-data="data" auto-legend></canvas>`

**Comment by joris-lambrechts** [comment]
You can now upgrade to version 2 which supports Chart.js 2!

**Comment by richfergus** [comment]
Thank you. Works.
