### ISSUE TITLE
How to manipulate scale, position, width and circumference of doughnut?

### ISSUE THREAD

**Issue by sujit7** [carlcraig/tc-angular-chartjs#70]

**Comment by carlcraig** [comment]
this is more of a chart.js question.

You most likely have Chart.js 1.X running, as this does not support 2.X just yet..

Take a look at the documentation for 1.X Chart.js https://github.com/chartjs/Chart.js/blob/v1.1.1/docs/05-Pie-Doughnut-Chart.md#chart-options

You should be able to change the options to do what you mention.

I will close this now, please let me know if you still have any issues.

**Comment by sujit7** [comment]
I've already gone through these. But I don't see any option fitting my requirements. But anyway, you can close. I'll see if I can find a work around for that.

**Comment by carlcraig** [comment]
i will reopen.. would you be able to outline in a bit more detail what you want to achieve? maybe someone else has done something similar

**Comment by sujit7** [comment]
Sure.. that will be good

**Comment by carlcraig** [comment]
Closing this for now, please look into the 2.X chart.js documentation, there might be a way to achieve this now.

**Comment by alwinkpc** [comment]
Nothing yet. Seems something as basic as set the circumference width cannot be done with this library
