### ISSUE TITLE
Options are not beign watched

### ISSUE THREAD

**Issue by Zeioth** [carlcraig/tc-angular-chartjs#76]
The graph is re-created after the data change, but ignores the new options. This is solved changing the line

    $scope.$watch('data', function(value) {

by

    $scope.$watch('[data, options]', function(value) {

**Comment by carlcraig** [comment]
Hiya, would you be able to create a PR for this by any chance?

**Comment by carlcraig** [comment]
This is fixed in `2.1.1`
