### ISSUE TITLE
Add support for inline plugins in Chart.js 

### ISSUE THREAD

**Issue by abarinoff** [carlcraig/tc-angular-chartjs#87]
Please add support for inline plugins introduced in Chart.js v2.5 or take a look at this pull request where this feature already implemented: https://github.com/carlcraig/tc-angular-chartjs/pull/86

Thanks!

**Comment by carlcraig** [comment]
Hi, i have merged your PR #86 

Thanks for contributing 👍 

I will close this issue now.
